#!/usr/bin/env bash
cp cdk.mixed.json cdk.json
cp config_stack.copy config_stack
cp pipeline_stack.mixed.copy pipeline_stack
cp secrets_stack.copy secrets_stack
cp secrets_deploy.copy secrets_deploy
chmod +x *_stack
chmod +x secrets_deploy
chmod +x update
rm composer.json
