export * from './permissions-bootstrap';
export * from './permissions-code-pipeline-ecs-stack';
//export * from './permissions-definitions';
export * from './permissions-dynamodb';
export * from './permissions-ecr';
export * from './permissions-ecs'
export * from './permissions-env-stack';
export * from './permissions-parameter';
export * from './permissions-queue';
export * from './permissions-s3';
export * from './permissions-ses';